/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as HakeemneurotechRouteImport } from './routes/hakeemneurotech'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicTtsRouteImport } from './routes/api/public/tts'
import { Route as ApiPublicTriggerRouteImport } from './routes/api/public/trigger'
import { Route as ApiPublicSolveRouteImport } from './routes/api/public/solve'
import { Route as ApiPublicNeuroRouteImport } from './routes/api/public/neuro'
import { Route as ApiPublicEventRouteImport } from './routes/api/public/event'
import { Route as ApiPublicAskRouteImport } from './routes/api/public/ask'
import { Route as ApiPublicBurstFinalizeRouteImport } from './routes/api/public/burst.finalize'

const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const HakeemneurotechRoute = HakeemneurotechRouteImport.update({
  id: '/hakeemneurotech',
  path: '/hakeemneurotech',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTtsRoute = ApiPublicTtsRouteImport.update({
  id: '/api/public/tts',
  path: '/api/public/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTriggerRoute = ApiPublicTriggerRouteImport.update({
  id: '/api/public/trigger',
  path: '/api/public/trigger',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSolveRoute = ApiPublicSolveRouteImport.update({
  id: '/api/public/solve',
  path: '/api/public/solve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNeuroRoute = ApiPublicNeuroRouteImport.update({
  id: '/api/public/neuro',
  path: '/api/public/neuro',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEventRoute = ApiPublicEventRouteImport.update({
  id: '/api/public/event',
  path: '/api/public/event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAskRoute = ApiPublicAskRouteImport.update({
  id: '/api/public/ask',
  path: '/api/public/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBurstFinalizeRoute = ApiPublicBurstFinalizeRouteImport.update({
  id: '/api/public/burst/finalize',
  path: '/api/public/burst/finalize',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hakeemneurotech': typeof HakeemneurotechRoute
  '/resources': typeof ResourcesRoute
  '/api/public/ask': typeof ApiPublicAskRoute
  '/api/public/event': typeof ApiPublicEventRoute
  '/api/public/neuro': typeof ApiPublicNeuroRoute
  '/api/public/solve': typeof ApiPublicSolveRoute
  '/api/public/trigger': typeof ApiPublicTriggerRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
  '/api/public/burst/finalize': typeof ApiPublicBurstFinalizeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hakeemneurotech': typeof HakeemneurotechRoute
  '/resources': typeof ResourcesRoute
  '/api/public/ask': typeof ApiPublicAskRoute
  '/api/public/event': typeof ApiPublicEventRoute
  '/api/public/neuro': typeof ApiPublicNeuroRoute
  '/api/public/solve': typeof ApiPublicSolveRoute
  '/api/public/trigger': typeof ApiPublicTriggerRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
  '/api/public/burst/finalize': typeof ApiPublicBurstFinalizeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hakeemneurotech': typeof HakeemneurotechRoute
  '/resources': typeof ResourcesRoute
  '/api/public/ask': typeof ApiPublicAskRoute
  '/api/public/event': typeof ApiPublicEventRoute
  '/api/public/neuro': typeof ApiPublicNeuroRoute
  '/api/public/solve': typeof ApiPublicSolveRoute
  '/api/public/trigger': typeof ApiPublicTriggerRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
  '/api/public/burst/finalize': typeof ApiPublicBurstFinalizeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hakeemneurotech'
    | '/resources'
    | '/api/public/ask'
    | '/api/public/event'
    | '/api/public/neuro'
    | '/api/public/solve'
    | '/api/public/trigger'
    | '/api/public/tts'
    | '/api/public/burst/finalize'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hakeemneurotech'
    | '/resources'
    | '/api/public/ask'
    | '/api/public/event'
    | '/api/public/neuro'
    | '/api/public/solve'
    | '/api/public/trigger'
    | '/api/public/tts'
    | '/api/public/burst/finalize'
  id:
    | '__root__'
    | '/'
    | '/hakeemneurotech'
    | '/resources'
    | '/api/public/ask'
    | '/api/public/event'
    | '/api/public/neuro'
    | '/api/public/solve'
    | '/api/public/trigger'
    | '/api/public/tts'
    | '/api/public/burst/finalize'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HakeemneurotechRoute: typeof HakeemneurotechRoute
  ResourcesRoute: typeof ResourcesRoute
  ApiPublicAskRoute: typeof ApiPublicAskRoute
  ApiPublicEventRoute: typeof ApiPublicEventRoute
  ApiPublicNeuroRoute: typeof ApiPublicNeuroRoute
  ApiPublicSolveRoute: typeof ApiPublicSolveRoute
  ApiPublicTriggerRoute: typeof ApiPublicTriggerRoute
  ApiPublicTtsRoute: typeof ApiPublicTtsRoute
  ApiPublicBurstFinalizeRoute: typeof ApiPublicBurstFinalizeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakeemneurotech': {
      id: '/hakeemneurotech'
      path: '/hakeemneurotech'
      fullPath: '/hakeemneurotech'
      preLoaderRoute: typeof HakeemneurotechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tts': {
      id: '/api/public/tts'
      path: '/api/public/tts'
      fullPath: '/api/public/tts'
      preLoaderRoute: typeof ApiPublicTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/trigger': {
      id: '/api/public/trigger'
      path: '/api/public/trigger'
      fullPath: '/api/public/trigger'
      preLoaderRoute: typeof ApiPublicTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/solve': {
      id: '/api/public/solve'
      path: '/api/public/solve'
      fullPath: '/api/public/solve'
      preLoaderRoute: typeof ApiPublicSolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/neuro': {
      id: '/api/public/neuro'
      path: '/api/public/neuro'
      fullPath: '/api/public/neuro'
      preLoaderRoute: typeof ApiPublicNeuroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/event': {
      id: '/api/public/event'
      path: '/api/public/event'
      fullPath: '/api/public/event'
      preLoaderRoute: typeof ApiPublicEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ask': {
      id: '/api/public/ask'
      path: '/api/public/ask'
      fullPath: '/api/public/ask'
      preLoaderRoute: typeof ApiPublicAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/burst/finalize': {
      id: '/api/public/burst/finalize'
      path: '/api/public/burst/finalize'
      fullPath: '/api/public/burst/finalize'
      preLoaderRoute: typeof ApiPublicBurstFinalizeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HakeemneurotechRoute: HakeemneurotechRoute,
  ResourcesRoute: ResourcesRoute,
  ApiPublicAskRoute: ApiPublicAskRoute,
  ApiPublicEventRoute: ApiPublicEventRoute,
  ApiPublicNeuroRoute: ApiPublicNeuroRoute,
  ApiPublicSolveRoute: ApiPublicSolveRoute,
  ApiPublicTriggerRoute: ApiPublicTriggerRoute,
  ApiPublicTtsRoute: ApiPublicTtsRoute,
  ApiPublicBurstFinalizeRoute: ApiPublicBurstFinalizeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
