/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicTtsRouteImport } from './routes/api/public/tts'
import { Route as ApiPublicTriggerRouteImport } from './routes/api/public/trigger'
import { Route as ApiPublicEventRouteImport } from './routes/api/public/event'
import { Route as ApiPublicBurstFinalizeRouteImport } from './routes/api/public/burst.finalize'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTtsRoute = ApiPublicTtsRouteImport.update({
  id: '/api/public/tts',
  path: '/api/public/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTriggerRoute = ApiPublicTriggerRouteImport.update({
  id: '/api/public/trigger',
  path: '/api/public/trigger',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEventRoute = ApiPublicEventRouteImport.update({
  id: '/api/public/event',
  path: '/api/public/event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBurstFinalizeRoute = ApiPublicBurstFinalizeRouteImport.update({
  id: '/api/public/burst/finalize',
  path: '/api/public/burst/finalize',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/event': typeof ApiPublicEventRoute
  '/api/public/trigger': typeof ApiPublicTriggerRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
  '/api/public/burst/finalize': typeof ApiPublicBurstFinalizeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/event': typeof ApiPublicEventRoute
  '/api/public/trigger': typeof ApiPublicTriggerRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
  '/api/public/burst/finalize': typeof ApiPublicBurstFinalizeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/event': typeof ApiPublicEventRoute
  '/api/public/trigger': typeof ApiPublicTriggerRoute
  '/api/public/tts': typeof ApiPublicTtsRoute
  '/api/public/burst/finalize': typeof ApiPublicBurstFinalizeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/event'
    | '/api/public/trigger'
    | '/api/public/tts'
    | '/api/public/burst/finalize'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/event'
    | '/api/public/trigger'
    | '/api/public/tts'
    | '/api/public/burst/finalize'
  id:
    | '__root__'
    | '/'
    | '/api/public/event'
    | '/api/public/trigger'
    | '/api/public/tts'
    | '/api/public/burst/finalize'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicEventRoute: typeof ApiPublicEventRoute
  ApiPublicTriggerRoute: typeof ApiPublicTriggerRoute
  ApiPublicTtsRoute: typeof ApiPublicTtsRoute
  ApiPublicBurstFinalizeRoute: typeof ApiPublicBurstFinalizeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tts': {
      id: '/api/public/tts'
      path: '/api/public/tts'
      fullPath: '/api/public/tts'
      preLoaderRoute: typeof ApiPublicTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/trigger': {
      id: '/api/public/trigger'
      path: '/api/public/trigger'
      fullPath: '/api/public/trigger'
      preLoaderRoute: typeof ApiPublicTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/event': {
      id: '/api/public/event'
      path: '/api/public/event'
      fullPath: '/api/public/event'
      preLoaderRoute: typeof ApiPublicEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/burst/finalize': {
      id: '/api/public/burst/finalize'
      path: '/api/public/burst/finalize'
      fullPath: '/api/public/burst/finalize'
      preLoaderRoute: typeof ApiPublicBurstFinalizeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicEventRoute: ApiPublicEventRoute,
  ApiPublicTriggerRoute: ApiPublicTriggerRoute,
  ApiPublicTtsRoute: ApiPublicTtsRoute,
  ApiPublicBurstFinalizeRoute: ApiPublicBurstFinalizeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
